const dataNavModal = [
  {
    id: 1,
    name: "Laptop",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["Acer", "Asus", "HP", "Del", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: [
      "Intel Core i8",
      "Intel Core i7",
      "Intel Core i6",
      "AMD Ryzen 3",
      "AMD Ryzen 6",
    ],
    Gia: "Lọc theo giá",
    listGia: [
      "Dưới 10 triệu",
      "10-15 triệu",
      "15-20 triệu",
      "20-25 triệu",
      "25-30 triệu",
      "Trên 30 triệu",
    ],
  },
  {
    id: 2,
    name: "LaptopGaming",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["Acer", "Asus", "HP", "Del", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: [
      "Intel Core i8",
      "Intel Core i7",
      "Intel Core i6",
      "AMD Ryzen 3",
      "AMD Ryzen 6",
    ],
    Gia: "Lọc theo giá",
    listGia: [
      "Dưới 10 triệu",
      "10-15 triệu",
      "15-20 triệu",
      "20-25 triệu",
      "25-30 triệu",
      "Trên 40 triệu",
    ],
  },
  {
    id: 3,
    name: "PC special",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["Acer", "Asus", "HP", "Del", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: [
      "Intel Core i8",
      "Intel Core i7",
      "Intel Core i6",
      "AMD Ryzen 3",
      "AMD Ryzen 6",
    ],
    Gia: "Lọc theo giá",
    listGia: [
      "Dưới 10 triệu",
      "10-15 triệu",
      "15-20 triệu",
      "20-25 triệu",
      "25-30 triệu",
      "Trên 40 triệu",
    ],
  },
];
export default dataNavModal;
