import {
  faComputer,
  faLaptop,
  faComputerMouse,
  faKeyboard,
  faTabletScreenButton,
} from "@fortawesome/free-solid-svg-icons";
const dataNavModal = [
  {
    id: 1,
    icon: faLaptop,
    name: "Laptop",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["Acer", "Asus", "HP", "Del", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: [
      "Intel Core i8",
      "Intel Core i7",
      "Intel Core i6",
      "AMD Ryzen 3",
      "AMD Ryzen 6",
    ],
    Gia: "Lọc theo giá",
    listGia: ["Dưới 10 triệu", "10-15 triệu", "15-20 triệu", "trên 20 triệu"],
  },
  {
    id: 2,
    icon: faComputer,
    name: "LaptopGaming",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["Acer", "Asus", "HP", "Del", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: [
      "Intel Core i8",
      "Intel Core i7",
      "Intel Core i6",
      "AMD Ryzen 3",
      "AMD Ryzen 6",
    ],
    Gia: "Lọc theo giá",
    listGia: [
      "Dưới 10 triệu",
      "10-15 triệu",
      "15-20 triệu",
      "20-25 triệu",
      "25-30 triệu",
      "Trên 40 triệu",
    ],
  },
  {
    id: 3,
    icon: faComputer,
    name: "PC special",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["Acer", "Asus", "HP", "Del", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: [
      "Intel Core i8",
      "Intel Core i7",
      "Intel Core i6",
      "AMD Ryzen 3",
      "AMD Ryzen 6",
    ],
    Gia: "Lọc theo giá",
    listGia: [
      "Dưới 10 triệu",
      "10-15 triệu",
      "15-20 triệu",
      "20-25 triệu",
      "25-30 triệu",
      "Trên 40 triệu",
    ],
  },
  {
    id: 4,
    icon: faTabletScreenButton,

    name: "Màn Hình",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["LG", "Asus", "Gigabity", "Del", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: ["60Hz", "75Hz", "100Hz", "144Hz", "240Hz"],
    Gia: "Lọc theo giá",
    listGia: [
      "Dưới 10 triệu",
      "10-15 triệu",
      "15-20 triệu",
      "20-25 triệu",
      "25-30 triệu",
      "Trên 40 triệu",
    ],
  },
  {
    id: 5,
    icon: faKeyboard,
    name: "Bàn Phím",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["Logitech", "Razer", "Crosair", "Asus", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: [
      "3068 Seria",
      "3068 Seria",
      "3084 Seria",
      "3087 Seria",
      "3088 Seria",
    ],
    Gia: "Lọc theo giá",
    listGia: [
      "Dưới 1 triệu",
      "1-1.5 triệu",
      "1.5-2 triệu",
      "2-2.5triệu",
      "Trên 3 triệu",
    ],
  },
  {
    id: 6,
    icon: faComputer,
    name: "PC Doanh nghiệp",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["Acer", "Asus", "HP", "Del", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: [
      "Intel Core i8",
      "Intel Core i7",
      "Intel Core i6",
      "AMD Ryzen 3",
      "AMD Ryzen 6",
    ],
    Gia: "Lọc theo giá",
    listGia: [
      "Dưới 10 triệu",
      "10-15 triệu",
      "15-20 triệu",
      "20-25 triệu",
      "25-30 triệu",
      "Trên 40 triệu",
    ],
  },
  {
    id: 7,
    icon: faComputerMouse,
    name: "Chuột",
    thuongHieu: "Lọc theo thương hiệu",
    listTH: ["Logitech", "Razer", "Crosair", "Asus", "MSI"],
    cauHinh: "Lọc theo cấu hình",
    listCH: [
      "3068 Seria",
      "3068 Seria",
      "3084 Seria",
      "3087 Seria",
      "3088 Seria",
    ],
    Gia: "Lọc theo giá",
    listGia: [
      "Dưới 1 triệu",
      "1-1.5 triệu",
      "1.5-2 triệu",
      "2-2.5triệu",
      "Trên 3 triệu",
    ],
  },
];
export default dataNavModal;
